version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    restart: always

  php:
    build:
      context: '.'
      dockerfile: ./docker/php/Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ./docker/php/conf.d/${ENVIRONMENT}.php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/php-fpm.d/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - ./src:/var/www/html
      - ./docker/bedrock/${ENVIRONMENT}.env:/var/www/html/.env
      - php-fpm-socket:/var/run/php-fpm
    depends_on:
      - mysql
    restart: always

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/conf.d/${ENVIRONMENT}.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
      - ./docker/bedrock/${ENVIRONMENT}.env:/var/www/html/.env
      - php-fpm-socket:/var/run/php-fpm
    ports:
      - 80:80
    depends_on:
      - php
    restart: always

volumes:
  php-fpm-socket:
